# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hell"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jose Diaz-Gonzalez"]
  s.date = "2013-01-04"
  s.description = "Hell is an open source web interface that exposes a set of capistrano recipes as a json api, for usage within large teams"
  s.email = "jose@seatgeek.com"
  s.executables = ["hell"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/hell",
    "config.ru",
    "hell.gemspec",
    "lib/hell.rb",
    "lib/hell/app.rb",
    "lib/hell/lib/capistrano/cli.rb",
    "lib/hell/lib/capistrano/configuration.rb",
    "lib/hell/lib/capistrano/task_definition.rb",
    "lib/hell/lib/cli.rb",
    "lib/hell/lib/helpers.rb",
    "lib/hell/lib/monkey_patch.rb",
    "lib/hell/public/assets/css/bootstrap-responsive.css",
    "lib/hell/public/assets/css/bootstrap-responsive.min.css",
    "lib/hell/public/assets/css/bootstrap.css",
    "lib/hell/public/assets/css/bootstrap.min.css",
    "lib/hell/public/assets/css/hell.css",
    "lib/hell/public/assets/ico/favicon.ico",
    "lib/hell/public/assets/ico/favicon.png",
    "lib/hell/public/assets/img/glyphicons-halflings-white.png",
    "lib/hell/public/assets/img/glyphicons-halflings.png",
    "lib/hell/public/assets/js/backbone-localstorage.js",
    "lib/hell/public/assets/js/backbone.js",
    "lib/hell/public/assets/js/bankersbox.js",
    "lib/hell/public/assets/js/bootstrap.growl.js",
    "lib/hell/public/assets/js/bootstrap.js",
    "lib/hell/public/assets/js/hashchange.js",
    "lib/hell/public/assets/js/hell.js",
    "lib/hell/public/assets/js/jquery.js",
    "lib/hell/public/assets/js/timeago.js",
    "lib/hell/public/assets/js/underscore.js",
    "lib/hell/views/index.erb",
    "test/helper.rb",
    "test/test_hell.rb",
    "unicorn"
  ]
  s.homepage = "http://github.com/seatgeek/hell"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A web interface and api wrapper around Capistrano"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>, [">= 0"])
      s.add_runtime_dependency(%q<pusher>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-assetpack>, [">= 0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<unicorn>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<multi_json>, [">= 0"])
      s.add_dependency(%q<pusher>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_dependency(%q<sinatra-assetpack>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<unicorn>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<multi_json>, [">= 0"])
    s.add_dependency(%q<pusher>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<sinatra-contrib>, [">= 0"])
    s.add_dependency(%q<sinatra-assetpack>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<unicorn>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

